import LegalPage from "@/components/LegalPage";

export const metadata = { title: "Privacy Policy — The Economic Times AI" };

export default function PrivacyPolicy() {
  return (
    <LegalPage
      title="Privacy Policy"
      subtitle="Last updated: March 26, 2026 | Effective Date: January 1, 2026"
      sections={[
        { heading: "Introduction", body: "Bennett, Coleman & Co. Ltd. ('we', 'our', 'us'), the publisher of The Economic Times, is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use The Economic Times AI News Experience platform. Please read this policy carefully. If you disagree with its terms, please discontinue use of the platform." },
        { heading: "Information We Collect", body: "We may collect information about you in a variety of ways. The information we may collect includes: (a) Personal Data — personally identifiable information, such as your name, email address, and demographic information that you voluntarily give to us when you register or when you choose to participate in various activities related to the platform; (b) Usage Data — information our servers automatically collect when you access the platform, such as your IP address, browser type, operating system, access times, and the pages you have viewed; (c) AI Interaction Data — queries, preferences, and interaction patterns with our AI features to improve personalisation and service quality." },
        { heading: "Use of Your Information", body: "Having accurate information about you permits us to provide you with a smooth, efficient, and customised experience. Specifically, we may use information collected about you to: personalise your news feed and AI recommendations; compile anonymous statistical data for internal use; deliver targeted advertising and editorial content; improve the efficiency and operation of the platform; monitor and analyse usage and trends; notify you of updates to our platform; and comply with applicable laws and regulations." },
        { heading: "AI and Data Processing", body: "The Economic Times AI News Experience uses artificial intelligence and machine learning technologies to personalise content, generate briefings, and provide analytical insights. Your interaction data may be processed by AI systems to improve the quality of recommendations. We do not use your personal data to train third-party AI models without your explicit consent. All AI processing is conducted in accordance with applicable data protection laws including the Digital Personal Data Protection Act, 2023 (DPDP Act)." },
        { heading: "Disclosure of Your Information", body: "We may share information we have collected about you in certain situations. Your information may be disclosed as follows: (a) By Law or to Protect Rights — if we believe the release of information about you is necessary to respond to legal process or to protect the rights, property, and safety of others; (b) Business Transfers — in connection with any merger, sale of company assets, or acquisition; (c) Third-Party Service Providers — we may share your information with third parties that perform services for us, including data analysis, email delivery, hosting services, and customer service; (d) Affiliates — we may share your information with our affiliates, including Times Internet Limited and other Bennett Coleman group companies." },
        { heading: "Security of Your Information", body: "We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse." },
        { heading: "Your Rights Under DPDP Act 2023", body: "Under the Digital Personal Data Protection Act, 2023, you have the right to: access your personal data held by us; correct inaccurate or incomplete personal data; erase your personal data in certain circumstances; nominate another individual to exercise your rights in the event of your death or incapacity; and file a complaint with the Data Protection Board of India. To exercise these rights, please contact our Data Protection Officer at dpo@economictimes.com." },
        { heading: "Contact Us", body: "If you have questions or comments about this Privacy Policy, please contact us at: Data Protection Officer, Bennett, Coleman & Co. Ltd., The Times of India Building, Dr. D.N. Road, Mumbai — 400 001. Email: dpo@economictimes.com | Phone: 1800-XXX-XXXX (Toll Free)" },
      ]}
    />
  );
}
