import { NextRequest, NextResponse } from "next/server";
import { readFileSync } from "fs";
import { join } from "path";

function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }

// Extra cards to cycle through for infinite scroll
const EXTRA_CARDS = [
  { id:"x1", headline:"Tata Motors EV sales cross 1 lakh units in a single month for first time", summary:"Tata Motors sold 1,02,340 electric vehicles in October 2026, crossing the 1 lakh monthly milestone for the first time. The Nexon EV and Punch EV together account for 78% of sales. Tata now commands 62% of India EV market. The company has announced a Rs15,000 crore investment in a new EV-only plant in Pune.", category:"Corporate", subcategory:"EV Market", sentiment:"positive", urgency:"today", readTime:"3 min", publishedAt:"2 hrs ago", keyNumber:{value:"1 Lakh+",label:"Monthly EV Sales"}, tags:["Tata Motors","EV","Electric Vehicle"], author:"ET Auto", hasChart:true, chartData:[20,35,48,62,78,102], chartTrend:"up", imageEmoji:"⚡", depth:"quick", relatedTopics:["Mahindra EV","Ola Electric"] },
  { id:"x2", headline:"Zomato Blinkit crosses Rs10,000 Cr quarterly revenue — quick commerce is now mainstream", summary:"Zomato reported consolidated quarterly revenue of Rs10,240 crore for Q2 FY27, with Blinkit contributing Rs3,800 crore — a 89% YoY jump. Blinkit now operates 1,200 dark stores across 40 cities. The unit economics have turned positive with contribution margin of 4.2%. Zomato stock hit a 52-week high of Rs285.", category:"Startups", subcategory:"Quick Commerce", sentiment:"positive", urgency:"today", readTime:"3 min", publishedAt:"4 hrs ago", keyNumber:{value:"Rs10,240 Cr",label:"Quarterly Revenue"}, tags:["Zomato","Blinkit","Quick Commerce"], author:"ET Startups", hasChart:true, chartData:[45,58,72,85,96,102], chartTrend:"up", imageEmoji:"🛵", depth:"deep", relatedTopics:["Zepto","Swiggy Instamart"] },
  { id:"x3", headline:"India overtakes Japan to become world third largest economy at $5.4 trillion", summary:"India GDP crossed $5.4 trillion in FY2026, overtaking Japan to become the world third largest economy. The milestone was achieved 2 years ahead of most forecasts. Per capita income has crossed $3,800. Prime Minister Modi called it a historic moment. The next target: $10 trillion by 2035.", category:"Economy", subcategory:"GDP Milestone", sentiment:"positive", urgency:"breaking", readTime:"2 min", publishedAt:"6 hrs ago", keyNumber:{value:"$5.4T",label:"India GDP"}, tags:["GDP","India Economy","Milestone"], author:"ET Bureau", hasChart:false, chartData:[], chartTrend:"up", imageEmoji:"🇮🇳", depth:"quick", relatedTopics:["India Growth Story","PM Modi Economy"] },
  { id:"x4", headline:"SEBI approves T+0 settlement for all stocks — India becomes first major market to do so", summary:"SEBI has approved same-day settlement (T+0) for all listed stocks from January 2027, making India the first major stock market globally to implement this. Currently only 25 stocks have T+0 settlement. The move will free up Rs2.5 lakh crore in blocked margin money. Brokers have 3 months to upgrade their systems.", category:"Markets", subcategory:"Market Structure", sentiment:"positive", urgency:"today", readTime:"4 min", publishedAt:"1 day ago", keyNumber:{value:"T+0",label:"Settlement Cycle"}, tags:["SEBI","Settlement","NSE","BSE"], author:"ET Markets", hasChart:false, chartData:[], chartTrend:"up", imageEmoji:"📊", depth:"deep", relatedTopics:["NSE","BSE","SEBI Reforms"] },
  { id:"x5", headline:"PhonePe IPO: $15B valuation, listing expected on NSE by March 2027", summary:"PhonePe has filed its Draft Red Herring Prospectus with SEBI for an IPO at a valuation of $15 billion. The company reported revenue of Rs5,200 crore and PAT of Rs197 crore in FY26 — its first profitable year. Walmart, which owns 85% of PhonePe, will not sell shares in the IPO. The issue size is Rs8,000 crore.", category:"Startups", subcategory:"IPO", sentiment:"positive", urgency:"today", readTime:"4 min", publishedAt:"3 hrs ago", keyNumber:{value:"$15B",label:"IPO Valuation"}, tags:["PhonePe","IPO","Fintech","Walmart"], author:"ET Startups", hasChart:false, chartData:[], chartTrend:"up", imageEmoji:"💳", depth:"deep", relatedTopics:["Paytm","Google Pay","UPI"] },
  { id:"x6", headline:"Coal India dividend yield hits 8.2% — PSU stocks are the new fixed income", summary:"Coal India declared an interim dividend of Rs25 per share, taking its trailing 12-month dividend to Rs62 per share — an 8.2% yield at current prices. PSU stocks as a category now offer average dividend yields of 5-6%, making them attractive alternatives to fixed deposits. LIC, ONGC, and NTPC are the other high-yield PSUs.", category:"Markets", subcategory:"Dividends", sentiment:"positive", urgency:"this-week", readTime:"3 min", publishedAt:"2 days ago", keyNumber:{value:"8.2%",label:"Dividend Yield"}, tags:["Coal India","PSU","Dividend","Yield"], author:"ET Markets", hasChart:true, chartData:[42,48,52,58,60,62], chartTrend:"up", imageEmoji:"💰", depth:"quick", relatedTopics:["ONGC","NTPC","LIC"] },
  { id:"x7", headline:"India AI startup Sarvam raises $165M — builds India first sovereign LLM", summary:"Bengaluru-based Sarvam AI has raised $165 million in a Series B round led by Lightspeed and Peak XV. The company has built India first large language model trained entirely on Indian languages and data. The model supports 10 Indian languages and is being deployed by IRCTC, SBI, and 3 state governments. Sarvam is valued at $800 million.", category:"Tech", subcategory:"AI Funding", sentiment:"positive", urgency:"today", readTime:"3 min", publishedAt:"5 hrs ago", keyNumber:{value:"$165M",label:"Series B Raised"}, tags:["Sarvam AI","LLM","India AI","Series B"], author:"ET Tech", hasChart:false, chartData:[], chartTrend:"up", imageEmoji:"🤖", depth:"deep", relatedTopics:["Krutrim","AI India","Bhashini"] },
  { id:"x8", headline:"Sensex crosses 90,000 for first time — retail investor count hits 15 crore", summary:"The BSE Sensex crossed 90,000 for the first time in history, driven by strong corporate earnings and FII inflows. India now has 15 crore registered stock market investors — up from 3 crore in 2019. SIP inflows hit a record Rs25,000 crore in October. The market cap to GDP ratio stands at 145%, above the historical average of 80%.", category:"Markets", subcategory:"Sensex Milestone", sentiment:"positive", urgency:"breaking", readTime:"2 min", publishedAt:"1 hr ago", keyNumber:{value:"90,000",label:"Sensex Level"}, tags:["Sensex","Bull Market","Retail Investors","SIP"], author:"ET Markets", hasChart:true, chartData:[55000,62000,70000,78000,85000,90000], chartTrend:"up", imageEmoji:"🚀", depth:"quick", relatedTopics:["Nifty 50","FII Flows","SIP"] },
];

export async function POST(req: NextRequest) {
  const { offset = 0 } = await req.json();
  await sleep(1200 + Math.random() * 600);

  try {
    // Cycle through extra cards with offset
    const batchSize = 5;
    const cards = [];
    for (let i = 0; i < batchSize; i++) {
      const idx = (offset + i) % EXTRA_CARDS.length;
      const card = { ...EXTRA_CARDS[idx], id: `${EXTRA_CARDS[idx].id}_${offset}_${i}` };
      cards.push(card);
    }
    return NextResponse.json({ cards, nextOffset: offset + batchSize });
  } catch {
    return NextResponse.json({ error: "Failed to fetch feed" }, { status: 500 });
  }
}
