import json, os

def q(s): return s.replace('"', "'")

investor = [
  ("i1","Nifty 50 hits all-time high of 26,277 as FII inflows surge Rs18,400 Cr","Foreign institutional investors pumped Rs18,400 crore into Indian equities - the highest single-week inflow since March 2023. IT and BFSI stocks led the rally. Analysts at Kotak Securities say the move is driven by Fed rate-cut expectations and India weight increase in MSCI EM index. Watch for profit-booking near 26,500.","Markets",97,"2 min read","positive","breaking","Nifty,FII,Bull Run,MSCI","14 mins ago","FII Inflow","Rs18,400 Cr","Your equity SIPs are now 12% up YTD - consider rebalancing if equity allocation exceeds your target."),
  ("i2","HDFC Flexi Cap Fund NAV crosses Rs1,000 mark - first Indian MF to do so","HDFC Flexi Cap Fund NAV touched Rs1,000 per unit, a milestone reflecting 28 years of compounding at 19.4% CAGR. The fund AUM stands at Rs62,000 crore. Fund manager Roshi Jain has increased allocation to PSU banks and capital goods. SIP investors who started in 2010 have seen 22x returns.","Markets",95,"3 min read","positive","today","HDFC MF,NAV,SIP,Flexi Cap","1 hr ago","NAV","Rs1,000","If you hold this fund, your SIP returns are compounding at near-benchmark levels - no action needed."),
  ("i3","RBI holds repo rate at 6.5% for 8th time; signals cut in Q2 FY27","The Monetary Policy Committee voted 4-2 to hold rates, citing food inflation at 6.2%. Governor Shaktikanta Das hinted at a 25bps cut in April 2027 if CPI falls below 4.5% sustainably. Debt fund managers are positioning in 10-year G-Secs anticipating a rate cycle turn. Short-duration funds saw Rs8,200 crore inflows this week.","Economy",92,"3 min read","neutral","today","RBI,Repo Rate,Debt Funds,MPC","3 hrs ago","Repo Rate","6.5%","Shift 10-15% of debt allocation to medium-duration funds now to benefit from the upcoming rate cut cycle."),
  ("i4","Smallcap index corrects 8% in 3 weeks - SEBI warns of froth in SME IPOs","The BSE Smallcap index has fallen 8.3% from its peak as SEBI issued a circular warning against price manipulation in SME IPOs. 23 SME IPOs have been put under surveillance. Mutual funds have reduced smallcap exposure by Rs4,200 crore. Valuations at 38x PE remain stretched versus historical average of 22x.","Markets",89,"4 min read","negative","today","Smallcap,SEBI,SME IPO,Valuation","5 hrs ago","Smallcap Fall","8.3%","If smallcap allocation exceeds 15% of portfolio, consider trimming - valuations do not justify current prices."),
  ("i5","Gold ETFs see record Rs3,400 Cr inflow as geopolitical tensions rise","Gold ETFs attracted Rs3,400 crore in October - the highest monthly inflow ever - as investors hedge against Middle East escalation and dollar weakness. Sovereign Gold Bonds 2023-24 Series II is trading at 14% premium on exchanges. Physical gold demand in India rose 18% YoY in Q3.","Commodities",84,"2 min read","positive","this-week","Gold ETF,SGB,Hedge,Geopolitical","8 hrs ago","Gold ETF Inflow","Rs3,400 Cr","Gold at 8-10% of portfolio acts as a hedge - SGBs offer additional 2.5% interest over physical gold."),
  ("i6","Axis Bluechip Fund underperforms benchmark for 6th consecutive quarter","Axis Bluechip Fund has underperformed the Nifty 100 TRI by 340 basis points over the last 18 months. The fund overweight position in consumer staples and underweight in IT has hurt returns. Morningstar downgraded the fund from Gold to Silver. AUM has fallen from Rs48,000 Cr to Rs41,000 Cr as investors exit.","Markets",88,"3 min read","negative","this-week","Axis MF,Underperformance,Large Cap,Fund Review","1 day ago","Underperformance","340 bps","Review your Axis Bluechip holding - consistent underperformance warrants switching to Mirae or Canara Robeco."),
  ("i7","Quant Mutual Fund under SEBI scanner for front-running - Rs93,000 Cr AUM at risk","SEBI is investigating Quant Mutual Fund for alleged front-running by its dealers. The fund house manages Rs93,000 crore across 26 schemes. Trading in Quant Small Cap and Quant Active Fund has been halted pending investigation. This is the largest front-running probe in Indian MF history.","Markets",94,"4 min read","negative","breaking","Quant MF,SEBI,Front Running,Investigation","2 hrs ago","AUM at Risk","Rs93,000 Cr","If you hold any Quant MF scheme, consider switching to a similar fund - regulatory risk is high right now."),
  ("i8","India current account deficit narrows to 0.9% of GDP - rupee strengthens","India CAD narrowed to 0.9% of GDP in Q2 FY26, the lowest in 11 quarters, driven by record services exports of 38 billion dollars. The rupee appreciated to 82.4 against the dollar. RBI forex reserves hit 698 billion dollars. Economists expect CAD to remain below 1.5% for FY26.","Economy",79,"3 min read","positive","this-week","CAD,Rupee,Forex,Macro","1 day ago","CAD/GDP","0.9%","Rupee stability reduces currency risk on international fund investments in your portfolio."),
]

founder = [
  ("f1","Zepto raises $350M Series G at $5B valuation - eyes IPO by Q3 2026","Quick-commerce startup Zepto closed a $350M round led by General Atlantic and Motilal Oswal, valuing it at $5B - up from $3.6B eight months ago. The company claims profitability in 12 of 17 cities. CEO Aadit Palicha confirmed IPO filing by September 2026. Rival Blinkit parent Zomato fell 3% on the news.","Startups",96,"3 min read","positive","breaking","Zepto,Series G,Quick Commerce,IPO","30 mins ago","Valuation","$5B","Zepto path to profitability before IPO sets a new benchmark - investors will now demand the same from you."),
  ("f2","DPDP Act enforcement begins April 2026 - startups face Rs250 Cr penalty risk","The Digital Personal Data Protection Act will be enforced from April 1, 2026. Startups collecting user data must appoint a Data Protection Officer, get explicit consent, and delete data within 30 days of user request. Non-compliance penalties go up to Rs250 crore. MeitY has released a compliance checklist for startups.","Policy",98,"5 min read","negative","breaking","DPDP Act,Data Privacy,Compliance,MeitY","2 hrs ago","Max Penalty","Rs250 Cr","You have 90 days to comply - prioritize consent management and data deletion workflows immediately."),
  ("f3","Peak XV closes $2.85B fund - largest India-SEA VC fund ever","Peak XV Partners formerly Sequoia India has closed a $2.85 billion fund, the largest ever raised for India and Southeast Asia. The fund will focus on AI, fintech, and consumer internet. Managing Director Rajan Anandan said 40% will go to seed and Series A. Average check size at Series A: $8-15 million.","Startups",93,"3 min read","positive","today","Peak XV,VC Funding,Series A,AI Startups","4 hrs ago","Fund Size","$2.85B","Peak XV is actively deploying - if you are raising Series A, this is the right time to get in their pipeline."),
  ("f4","RBI new fintech SRO framework - what it means for payment startups","RBI has mandated all fintech companies with over 10 lakh users to register with the newly formed Fintech Self-Regulatory Organisation by June 2026. The SRO will set conduct norms, handle grievances, and report to RBI quarterly. Payment aggregators must maintain a Rs25 crore net worth. 340 fintechs are affected.","Policy",91,"4 min read","neutral","today","RBI,Fintech SRO,Regulation,Payments","6 hrs ago","Net Worth Req.","Rs25 Cr","Register with the SRO early - late registrations will face scrutiny and potential license delays."),
  ("f5","India B2B SaaS exports cross $10B - Bessemer bets big on vertical SaaS","Indian B2B SaaS companies exported $10.2 billion in FY26, growing 34% YoY. Bessemer Venture Partners has committed $500M specifically for Indian vertical SaaS targeting US mid-market. Companies like Darwinbox, Leadsquared, and Chargebee are expanding US GTM teams. Average ARR multiple for Indian SaaS: 8-12x.","Startups",87,"4 min read","positive","this-week","SaaS,B2B,Exports,Bessemer","1 day ago","SaaS Exports","$10.2B","US mid-market is the highest-value segment for Indian SaaS - if you are not there yet, now is the time."),
  ("f6","Byjus insolvency: NCLT admits creditor petition - $1.2B in claims pending","The National Company Law Tribunal has admitted an insolvency petition against Byjus filed by the Board of Control for Cricket in India over Rs158 crore in unpaid dues. Total creditor claims stand at $1.2 billion. The resolution professional has been appointed. 22,000 employees face uncertainty over salaries.","Startups",82,"5 min read","negative","today","Byjus,Insolvency,NCLT,Edtech","8 hrs ago","Claims Pending","$1.2B","Byjus collapse is reshaping edtech investor sentiment - expect tighter due diligence and lower valuations in the sector."),
  ("f7","ONDC hits 10 lakh daily orders - threatens Swiggy and Zomato duopoly","Open Network for Digital Commerce processed 10 lakh daily orders in October 2026, up from 2 lakh a year ago. Food delivery on ONDC is 15-20% cheaper for consumers due to zero platform commission. Swiggy market share has fallen from 45% to 38% in metro cities. 1,200 new restaurants joined ONDC this month.","Tech",85,"3 min read","neutral","this-week","ONDC,Food Delivery,Swiggy,Zomato","1 day ago","Daily Orders","10 Lakh","If you are in commerce or logistics, ONDC integration is now a competitive necessity, not an option."),
  ("f8","Startup India Seed Fund Scheme 2.0 - Rs1,000 Cr for 3,000 startups","DPIIT has launched Startup India Seed Fund Scheme 2.0 with a Rs1,000 crore corpus to fund 3,000 early-stage startups. Grant of up to Rs20 lakh for proof-of-concept and Rs50 lakh for market entry. Applications open November 15. Priority sectors: deeptech, agritech, healthtech, and climate tech.","Policy",90,"3 min read","positive","today","DPIIT,Seed Fund,Government Grant,Early Stage","5 hrs ago","Fund Corpus","Rs1,000 Cr","If you are pre-Series A, this grant does not dilute equity - apply before the November 15 deadline."),
]

student = [
  ("s1","What is the Union Budget and why does every Indian business care about it?","The Union Budget is the government annual financial plan - it decides how much money India collects in taxes and spends on roads, schools, and defence. For businesses, it is like a rulebook reset every year. When the Finance Minister raises import duties on electronics, companies like Apple must rethink their India pricing. When she cuts corporate tax, companies have more money to hire and expand.","Economy",95,"5 min read","neutral","this-week","Budget Explainer,Fiscal Policy,Taxes,Beginner","2 hrs ago","India Budget Size","Rs47.65 Lakh Cr","Understanding the budget helps you predict which sectors will boom - and which stocks or careers to pursue."),
  ("s2","Why did Byjus - once India most valuable startup - collapse so spectacularly?","Byjus was valued at $22 billion in 2022. By 2026, it is in insolvency. The reasons: it raised $5 billion but spent it on acquisitions instead of building a sustainable business. It hid losses, delayed audits, and misled investors. The lesson: growth without profitability is a ticking time bomb. Revenue of Rs5,000 crore meant nothing when losses were Rs8,000 crore.","Startups",93,"6 min read","negative","today","Byjus,Case Study,Startup Failure,Edtech","3 hrs ago","Peak Valuation","$22B","This is the most important MBA case study of the decade - understanding it will make you a sharper analyst."),
  ("s3","Explained: What is a repo rate and how does it affect your home loan EMI?","The repo rate is the interest rate at which RBI lends money to banks. When RBI raises it, banks borrow at higher cost and pass it to you as higher EMIs. India repo rate is 6.5% today. A 0.25% hike on a Rs50 lakh home loan adds Rs850 to your monthly EMI. RBI uses this tool to control inflation - higher rates make borrowing expensive, reducing spending.","Banking",91,"4 min read","neutral","this-week","Repo Rate,EMI,RBI,Explainer","5 hrs ago","Current Repo Rate","6.5%","Every finance interview asks about monetary policy - this is your foundation."),
  ("s4","India GDP grows 7.2% - but what does GDP actually measure?","GDP or Gross Domestic Product is the total value of all goods and services produced in India in a year. Think of it as India Inc. annual revenue. At 7.2% growth, India added roughly $220 billion to its economy this quarter. But GDP does not measure inequality - India can grow 7% while millions remain poor. That is why economists also track per-capita income and Gini coefficient.","Economy",89,"5 min read","positive","today","GDP,Macroeconomics,India Growth,Explainer","6 hrs ago","GDP Growth","7.2%","GDP is the first number every analyst, investor, and policymaker looks at - know it cold."),
  ("s5","How Reliance Industries became a Rs20 lakh crore company - a business model breakdown","Reliance started as a textile company in 1966. Today it is in oil, telecom, retail, and media. The secret: vertical integration. Reliance refines oil, sells petrol, uses profits to build Jio, uses Jio 450 million users to sell through JioMart. Each business feeds the next. This flywheel model is why Mukesh Ambani net worth exceeds India defence budget.","Corporate",87,"7 min read","positive","this-week","Reliance,Business Model,Conglomerate,Case Study","1 day ago","Market Cap","Rs20 Lakh Cr","Reliance strategy is a masterclass in diversification - expect case study questions on this in every B-school interview."),
  ("s6","What is SEBI and why does it matter for stock market investors?","SEBI or Securities and Exchange Board of India is the stock market police force. It ensures companies do not cheat investors, brokers do not manipulate prices, and mutual funds are transparent. When Quant MF was caught front-running, SEBI froze their trades within 48 hours. Without SEBI, the stock market would be like cricket without an umpire.","Markets",85,"4 min read","neutral","this-week","SEBI,Regulation,Stock Market,Explainer","1 day ago","SEBI Established","1992","SEBI questions appear in every finance exam and interview - understand its powers and limitations."),
  ("s7","India startup ecosystem explained: from idea to IPO in 5 steps","Step 1: Idea plus bootstrapping. Step 2: Angel funding Rs25-50 lakh for 5-10% equity. Step 3: Seed round $500K to $2M. Step 4: Series A B C for scaling. Step 5: IPO or acquisition. Most startups die at Step 2. Only 1 in 100 seed-funded startups reach Series B. Understanding this funnel helps you evaluate startup job offers and career risk.","Startups",92,"6 min read","positive","this-week","Startup Ecosystem,Funding Stages,IPO,Career","2 days ago","India Unicorns","115","If you are considering a startup job, knowing the funding stage tells you how much runway the company has."),
  ("s8","Inflation at 5.1% - why rising prices hurt the poor more than the rich","India retail inflation is 5.1%, driven by vegetable prices up 42% YoY. But inflation hits differently across income groups. A family spending 60% of income on food suffers far more than one spending 15%. This is why RBI targets 4% inflation - it is a social equity issue, not just an economic one. Core inflation at 3.9% shows demand-side pressures are easing.","Economy",88,"5 min read","negative","today","Inflation,CPI,Inequality,RBI","8 hrs ago","CPI Inflation","5.1%","Inflation analysis is core to any economics or finance role - this framing will impress interviewers."),
]

executive = [
  ("e1","Tata Group Rs90,000 Cr semiconductor play - inside the Dholera fab strategy","Tata Electronics is investing Rs91,000 crore in a semiconductor fabrication plant in Dholera, Gujarat - India first commercial chip fab. The plant will produce 28nm chips for automotive and industrial use, with production starting Q4 2026. PSMC of Taiwan is the technology partner. The Indian government is co-investing Rs27,000 crore under the India Semiconductor Mission.","Corporate",97,"5 min read","positive","today","Tata,Semiconductor,Dholera,Manufacturing","1 hr ago","Investment","Rs91,000 Cr","India semiconductor push creates supply chain opportunities - evaluate component sourcing strategy now."),
  ("e2","McKinsey India: 40% of white-collar jobs face AI disruption by 2028","McKinsey latest India Future of Work report estimates 40% of white-collar roles - 18 million jobs - face significant AI disruption by 2028. Most at risk: data entry, basic analysis, customer service, and junior legal work. Roles growing fastest: AI trainers, prompt engineers, and human-AI collaboration managers. Companies that reskill now will have 3x productivity advantage.","Corporate",95,"6 min read","negative","today","AI Disruption,Future of Work,McKinsey,Workforce","3 hrs ago","Jobs at Risk","18 Million","Board-level decision: allocate 2-3% of payroll to AI reskilling now or face talent crisis by 2027."),
  ("e3","HDFC Bank-HDFC merger: 18 months later - what worked and what did not","The HDFC-HDFC Bank merger completed in July 2023 created India largest private bank with Rs25 lakh crore in assets. The integration has been smoother than expected - NIM compression of 20bps was within guidance. However, the home loan book growth has slowed to 8% vs the pre-merger 14%. MD Sashidhar Jagdishan biggest challenge: retaining HDFC relationship-banking culture.","Banking",91,"7 min read","neutral","this-week","HDFC Bank,Merger,Integration,Banking Strategy","6 hrs ago","Combined Assets","Rs25 Lakh Cr","The HDFC merger is the benchmark for large-scale financial services M&A in India - study it before your next deal."),
  ("e4","India PLI scheme: Rs2.5 lakh Cr disbursed - which sectors are winning?","The Production Linked Incentive scheme has disbursed Rs2.5 lakh crore across 14 sectors since 2020. Electronics led by Apple suppliers and pharmaceuticals are the clear winners with 340% and 180% production growth respectively. Auto components and specialty chemicals are underperforming targets by 40%. The scheme has created 8.5 lakh direct jobs.","Policy",88,"5 min read","positive","this-week","PLI Scheme,Manufacturing,Make in India,Policy","1 day ago","PLI Disbursed","Rs2.5 Lakh Cr","If your sector has an active PLI scheme, your competitors are already claiming incentives - are you?"),
  ("e5","Infosys TCS Wipro lose 45,000 employees to GCCs - the talent war is real","Global Capability Centres in India now employ 1.9 million people, up from 1.1 million in 2021. They are paying 30-40% premiums over IT services companies. Infosys, TCS, and Wipro collectively lost 45,000 mid-level employees to GCCs in FY26. The average GCC salary for a 5-year experience engineer: Rs28 lakh vs Rs19 lakh at IT services firms.","Corporate",86,"4 min read","negative","today","GCC,IT Talent,Attrition,Infosys","8 hrs ago","GCC Employees","1.9 Million","Retention strategy must include GCC-competitive compensation - benchmark your bands against GCC pay scales."),
  ("e6","ESG reporting mandatory for top 1,000 listed companies from FY27 - SEBI framework","SEBI Business Responsibility and Sustainability Reporting framework becomes mandatory for the top 1,000 listed companies from FY2026-27. Companies must disclose Scope 1, 2, and 3 emissions, water usage, and supply chain ESG metrics. Third-party assurance is required for Scope 1 and 2. Non-compliance attracts Rs1 crore per quarter penalty.","Policy",84,"5 min read","neutral","this-week","ESG,BRSR,SEBI,Sustainability","2 days ago","Companies Affected","Top 1,000","Start Scope 3 data collection now - supply chain emissions data takes 12-18 months to compile accurately."),
  ("e7","Reliance-Disney JV: Rs8,500 Cr deal creates India largest media company","Reliance Industries and The Walt Disney Company have completed their Rs8,500 crore joint venture, merging Star India with Jio Cinema. The combined entity controls 120 TV channels, 2 OTT platforms, and IPL broadcast rights worth $6 billion. The JV has 750 million monthly active users - more than Netflix globally. Uday Shankar is the CEO.","Corporate",90,"4 min read","positive","today","Reliance,Disney,JV,Media,OTT","4 hrs ago","JV Value","Rs8,500 Cr","The media consolidation changes advertising strategy - OTT-first campaigns now reach 750M users through one deal."),
  ("e8","India logistics cost falls to 8.5% of GDP - still 2x higher than US benchmark","India logistics cost as a percentage of GDP has fallen from 14% in 2014 to 8.5% in 2026, driven by GST, dedicated freight corridors, and PM Gati Shakti. However, the US benchmark is 4% and China is at 6%. The remaining gap costs Indian exporters $180 billion annually in competitiveness. Last-mile delivery remains the biggest bottleneck.","Economy",82,"4 min read","neutral","this-week","Logistics,Supply Chain,Gati Shakti,Exports","1 day ago","Logistics Cost/GDP","8.5%","Every 1% reduction in logistics cost adds 0.3% to your export margins - map your supply chain against freight corridors."),
]

def make_obj(a):
    tags = json.dumps([t.strip() for t in a[8].split(",")])
    return f'{{id:"{a[0]}",title:"{q(a[1])}",summary:"{q(a[2])}",category:"{a[3]}",relevanceScore:{a[4]},readTime:"{a[5]}",sentiment:"{a[6]}",urgency:"{a[7]}",tags:{tags},publishedAt:"{a[9]}",keyMetric:{{label:"{a[10]}",value:"{a[11]}"}},whyItMatters:"{q(a[12])}"}}'

out = ["// Demo data - no API key needed\nexport const DEMO_FEEDS: Record<string, any[]> = {"]
for name, data in [("investor", investor), ("founder", founder), ("student", student), ("executive", executive)]:
    out.append(f"  {name}: [")
    for a in data:
        out.append(f"    {make_obj(a)},")
    out.append("  ],")
out.append("};")

with open("lib/demo-data.ts", "w", encoding="utf-8") as f:
    f.write("\n".join(out))
print("feeds written:", len(out), "lines")
